version: "3.3"
services:
  db:
    image: "mysql:5.7.37-oracle"
    volumes:
      - "./.mysql-data/db:/var/lib/mysql"
    environment:
      - MYSQL_ROOT_PASSWORD=kanbanpassword
      - MYSQL_DATABASE=kanbandb
  web:
    build: .
    volumes:
      - "./uploads:/var/lib/uploads"
    ports:
      - "49901:80"
      - "49902:443"